repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.3
    hooks:
      - id: ruff
        name: Ruff Lint + Fix
        args: ["--select=E,F,I", "--line-length=120", "--fix"]
      - id: ruff-format
        name: Ruff Format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        additional_dependencies: ["types-requests", "types-urllib3"]  # added stub packages
        args: ["--config-file=mypy.ini"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
