[mypy]
python_version = 3.11
ignore_missing_imports = True
warn_unused_ignores = True
show_error_codes = True
pretty = True

# Exclude all migration files from analysis (regex on file path)
exclude = .*/migrations/.*

[mypy-*.migrations.*]
ignore_errors = True
