# Generated by Django 5.2.8 on 2025-11-23 18:19

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "albums",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("sha256", models.CharField(db_index=True, max_length=64, unique=True)),
                ("storage_key", models.CharField(max_length=1024)),
                ("mime_type", models.CharField(max_length=100)),
                ("width", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
                ("taken_at", models.DateTimeField(blank=True, null=True)),
                (
                    "description",
                    models.TextField(blank=True, help_text="User-provided description or caption for this photo"),
                ),
                ("phash", models.CharField(blank=True, db_index=True, max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="StorageBackend",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "backend_type",
                    models.CharField(
                        choices=[("s3", "Amazon S3"), ("minio", "MinIO"), ("local", "Local File System")], max_length=10
                    ),
                ),
                ("endpoint_url", models.URLField(blank=True)),
                ("region", models.CharField(blank=True, max_length=50)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "storage_backends",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AlbumAsset",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("album", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="assets.album")),
                ("asset", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="assets.asset")),
            ],
            options={
                "db_table": "album_assets",
                "ordering": ["order", "created_at"],
                "unique_together": {("album", "asset")},
            },
        ),
        migrations.AddField(
            model_name="album",
            name="assets",
            field=models.ManyToManyField(related_name="albums", through="assets.AlbumAsset", to="assets.asset"),
        ),
        migrations.AddField(
            model_name="album",
            name="cover_asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cover_for_albums",
                to="assets.asset",
            ),
        ),
        migrations.CreateModel(
            name="StorageBucket",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("display_name", models.CharField(max_length=100)),
                (
                    "purpose",
                    models.CharField(
                        choices=[("originals", "Original Photos"), ("thumbnails", "Thumbnails")],
                        default="originals",
                        max_length=20,
                    ),
                ),
                ("is_public", models.BooleanField(default=False)),
                ("path_prefix", models.CharField(blank=True, max_length=500)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "backend",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="buckets", to="assets.storagebackend"
                    ),
                ),
            ],
            options={
                "db_table": "storage_buckets",
                "ordering": ["backend", "purpose", "display_name"],
                "unique_together": {("backend", "name")},
            },
        ),
        migrations.AddField(
            model_name="asset",
            name="storage_bucket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="assets", to="assets.storagebucket"
            ),
        ),
        migrations.CreateModel(
            name="UploadBatch",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total_files", models.PositiveIntegerField(default=0)),
                ("processed_files", models.PositiveIntegerField(default=0)),
                ("failed_files", models.PositiveIntegerField(default=0)),
                (
                    "default_keywords",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100), blank=True, default=list, size=None
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
                (
                    "default_album",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="assets.album"
                    ),
                ),
            ],
            options={
                "db_table": "upload_batches",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AssetThumbnail",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("xs", "Extra Small (150px)"),
                            ("sm", "Small (300px)"),
                            ("md", "Medium (600px)"),
                            ("lg", "Large (1200px)"),
                        ],
                        max_length=2,
                    ),
                ),
                ("storage_key", models.CharField(max_length=1024)),
                ("width", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
                ("file_size", models.PositiveIntegerField()),
                ("is_ready", models.BooleanField(default=False)),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="thumbnails", to="assets.asset"
                    ),
                ),
                (
                    "storage_bucket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thumbnails",
                        to="assets.storagebucket",
                    ),
                ),
            ],
            options={
                "ordering": ["size"],
                "indexes": [
                    models.Index(fields=["asset", "size"], name="assets_asse_asset_i_b204e6_idx"),
                    models.Index(fields=["is_ready"], name="assets_asse_is_read_a7bbd7_idx"),
                ],
                "unique_together": {("asset", "size")},
            },
        ),
    ]
