# Generated by Django 5.2.8 on 2025-11-24 01:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storagebackend",
            name="endpoint_url",
        ),
        migrations.RemoveField(
            model_name="storagebackend",
            name="region",
        ),
        migrations.AlterField(
            model_name="storagebackend",
            name="backend_type",
            field=models.CharField(choices=[("local", "Local File System")], default="local", max_length=10),
        ),
        migrations.AlterField(
            model_name="storagebackend",
            name="config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Configuration dict. For local storage, must contain 'base_path' key with filesystem path.",
            ),
        ),
    ]
