# Generated by Django 5.2.8 on 2025-11-26 13:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0002_comment_like"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="asset",
            options={"ordering": ["-taken_at", "-created_at"]},
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["-taken_at", "-created_at"], name="assets_asse_taken_a_80fcc1_idx"),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["owner"], name="assets_asse_owner_i_bd5223_idx"),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["storage_bucket"], name="assets_asse_storage_91b110_idx"),
        ),
    ]
