# Generated by Django 5.2.8 on 2025-11-24 02:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0002_remove_storagebackend_endpoint_url_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UploadBatch",
        ),
    ]
