# Generated by Django 5.2.8 on 2025-11-25 00:54

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL("CREATE EXTENSION IF NOT EXISTS vector;"),
        migrations.CreateModel(
            name="KeywordTag",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("color", models.CharField(blank=True, max_length=7)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="metadata.keywordtag",
                    ),
                ),
            ],
            options={
                "db_table": "keyword_tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AssetKeyword",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("exif", "EXIF Data"),
                            ("ai", "AI Generated"),
                            ("batch", "Batch Import"),
                        ],
                        default="manual",
                        max_length=10,
                    ),
                ),
                ("confidence", models.FloatField(default=1.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("asset", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="assets.asset")),
                ("keyword", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="metadata.keywordtag")),
            ],
            options={
                "db_table": "asset_keywords",
            },
        ),
        migrations.CreateModel(
            name="XmpSidecar",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("sidecar_path", models.CharField(blank=True, max_length=1024)),
                ("sidecar_size", models.PositiveIntegerField(blank=True, null=True)),
                ("sidecar_checksum", models.CharField(blank=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("writing", "Writing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("last_write_attempt", models.DateTimeField(blank=True, null=True)),
                ("write_error", models.TextField(blank=True)),
                ("includes_faces", models.BooleanField(default=False)),
                ("includes_keywords", models.BooleanField(default=False)),
                ("includes_caption", models.BooleanField(default=False)),
                ("includes_gps", models.BooleanField(default=False)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="xmp_sidecar", to="assets.asset"
                    ),
                ),
            ],
            options={
                "db_table": "xmp_sidecars",
            },
        ),
        migrations.CreateModel(
            name="AssetMetadata",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("exif_data", models.JSONField(blank=True, default=dict)),
                ("camera_make", models.CharField(blank=True, max_length=100)),
                ("camera_model", models.CharField(blank=True, max_length=100)),
                ("lens_model", models.CharField(blank=True, max_length=100)),
                ("iso", models.PositiveIntegerField(blank=True, null=True)),
                ("aperture", models.CharField(blank=True, max_length=10, null=True)),
                ("shutter_speed", models.CharField(blank=True, max_length=20, null=True)),
                ("focal_length", models.CharField(blank=True, max_length=20, null=True)),
                ("gps_latitude", models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ("gps_longitude", models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ("gps_altitude", models.FloatField(blank=True, null=True)),
                ("location_name", models.CharField(blank=True, max_length=255)),
                ("color_space", models.CharField(blank=True, max_length=50)),
                ("white_balance", models.CharField(blank=True, max_length=50)),
                ("flash_fired", models.BooleanField(blank=True, null=True)),
                ("software", models.CharField(blank=True, max_length=100)),
                ("processing_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="metadata", to="assets.asset"
                    ),
                ),
            ],
            options={
                "db_table": "asset_metadata",
                "indexes": [
                    models.Index(fields=["camera_make", "camera_model"], name="asset_metad_camera__183cf9_idx"),
                    models.Index(fields=["iso"], name="asset_metad_iso_12e8e0_idx"),
                    models.Index(fields=["gps_latitude", "gps_longitude"], name="asset_metad_gps_lat_acdb35_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ClipEmbedding",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("embedding", pgvector.django.vector.VectorField(dimensions=512)),
                ("model_name", models.CharField(default="ViT-B/32", max_length=100)),
                ("model_version", models.CharField(blank=True, max_length=50)),
                ("processing_time_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("image_size_used", models.CharField(blank=True, max_length=20)),
                ("embedding_norm", models.FloatField(blank=True, null=True)),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="clip_embedding", to="assets.asset"
                    ),
                ),
            ],
            options={
                "db_table": "clip_embeddings",
                "indexes": [
                    models.Index(fields=["model_name"], name="clip_embedd_model_n_52ed4e_idx"),
                    models.Index(fields=["-created_at"], name="clip_embedd_created_b1946b_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="keywordtag",
            index=models.Index(fields=["parent"], name="keyword_tag_parent__4d8f4a_idx"),
        ),
        migrations.AddIndex(
            model_name="keywordtag",
            index=models.Index(fields=["-usage_count"], name="keyword_tag_usage_c_54173a_idx"),
        ),
        migrations.AddIndex(
            model_name="assetkeyword",
            index=models.Index(fields=["source"], name="asset_keywo_source_86aa79_idx"),
        ),
        migrations.AddIndex(
            model_name="assetkeyword",
            index=models.Index(fields=["-confidence"], name="asset_keywo_confide_0d5c17_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="assetkeyword",
            unique_together={("asset", "keyword")},
        ),
        migrations.AddIndex(
            model_name="xmpsidecar",
            index=models.Index(fields=["status"], name="xmp_sidecar_status_35b8ba_idx"),
        ),
        migrations.AddIndex(
            model_name="xmpsidecar",
            index=models.Index(fields=["-last_write_attempt"], name="xmp_sidecar_last_wr_fa12a0_idx"),
        ),
    ]
