# Generated by Django 5.2.6 on 2025-09-12 04:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServerConfiguration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("config_file", models.BooleanField(default=False)),
                ("duplicate_detection", models.BooleanField(default=False)),
                ("email", models.BooleanField(default=False)),
                ("facial_recognition", models.BooleanField(default=True)),
                ("import_faces", models.BooleanField(default=False)),
                ("map", models.BooleanField(default=True)),
                ("oauth", models.BooleanField(default=False)),
                ("oauth_auto_launch", models.BooleanField(default=False)),
                ("password_login", models.BooleanField(default=True)),
                ("reverse_geocoding", models.BooleanField(default=True)),
                ("search", models.BooleanField(default=True)),
                ("sidecar", models.BooleanField(default=True)),
                ("smart_search", models.BooleanField(default=True)),
                ("trash", models.BooleanField(default=True)),
                ("external_domain", models.CharField(blank=True, default="", max_length=255)),
                ("is_initialized", models.BooleanField(default=False)),
                ("is_onboarded", models.BooleanField(default=False)),
                ("login_page_message", models.TextField(blank=True, default="")),
                ("map_dark_style_url", models.URLField(blank=True, default="")),
                ("map_light_style_url", models.URLField(blank=True, default="")),
                ("oauth_button_text", models.CharField(blank=True, default="Login with OAuth", max_length=100)),
                ("public_users", models.BooleanField(default=True)),
                ("trash_days", models.IntegerField(default=30)),
                ("user_delete_delay", models.IntegerField(default=7)),
                ("supported_image_types", models.JSONField(blank=True, default=list)),
                ("supported_sidecar_types", models.JSONField(blank=True, default=list)),
                ("supported_video_types", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Server Configuration",
                "verbose_name_plural": "Server Configurations",
            },
        ),
    ]
