# Generated by Django 5.2.6 on 2025-09-12 14:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("config", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="serverconfiguration",
            name="is_initialized",
        ),
        migrations.RemoveField(
            model_name="serverconfiguration",
            name="is_onboarded",
        ),
    ]
