# Generated by Django 5.2.8 on 2025-11-23 18:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSharingProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True)),
                ('default_show_faces', models.BooleanField(default=True)),
                ('default_show_names', models.BooleanField(default=True)),
                ('default_allow_downloads', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_sharing_profiles', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sharing_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_sharing_profiles',
                'ordering': ['user__first_name', 'user__last_name', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='AccessGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grant_type', models.CharField(choices=[('album', 'Album Access'), ('person', 'Person Access')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='assets.album')),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='people.person')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'access_grants',
                'indexes': [models.Index(fields=['user', 'grant_type'], name='access_gran_user_id_492101_idx'), models.Index(fields=['album'], name='access_gran_album_i_2a0b87_idx'), models.Index(fields=['person'], name='access_gran_person__2da332_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('album__isnull', False), ('person__isnull', True)), models.Q(('album__isnull', True), ('person__isnull', False)), _connector='OR'), name='exactly_one_grant_target'), models.UniqueConstraint(condition=models.Q(('album__isnull', False)), fields=('user', 'album'), name='unique_user_album_grant'), models.UniqueConstraint(condition=models.Q(('person__isnull', False)), fields=('user', 'person'), name='unique_user_person_grant')],
            },
        ),
        migrations.CreateModel(
            name='SharingLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('password_hash', models.CharField(blank=True, max_length=128)),
                ('show_faces', models.BooleanField(blank=True, null=True)),
                ('show_names', models.BooleanField(blank=True, null=True)),
                ('allow_downloads', models.BooleanField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('access_count', models.PositiveIntegerField(default=0)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sharing_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sharing_links',
                'indexes': [models.Index(fields=['token_hash'], name='sharing_lin_token_h_038342_idx'), models.Index(fields=['expires_at'], name='sharing_lin_expires_9de4c2_idx'), models.Index(fields=['user'], name='sharing_lin_user_id_db3dee_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_grants', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_with_users', to='assets.asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_assets',
                'indexes': [models.Index(fields=['user', 'asset'], name='user_assets_user_id_d94f1e_idx'), models.Index(fields=['asset'], name='user_assets_asset_i_952251_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'asset'), name='unique_user_asset')],
            },
        ),
        migrations.CreateModel(
            name='UserAssetRebuildLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_type', models.CharField(max_length=50)),
                ('trigger_details', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=10)),
                ('assets_added', models.PositiveIntegerField(default=0)),
                ('assets_removed', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_rebuild_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_asset_rebuild_logs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', '-started_at'], name='user_asset__user_id_aff3c9_idx'), models.Index(fields=['status'], name='user_asset__status_ffc498_idx')],
            },
        ),
    ]
